### ISSUE TITLE
example config file bug with ?

### ISSUE THREAD

**Issue by rienafairefr** [napisani/procmux#26]
Ran the project to test it out, and immediately got a stack trace when using the example config (https://github.com/napisani/procmux#configuration)
```
❯ procmux --config mux.op.yml 
Traceback (most recent call last):
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/cache.py", line 35, in get
    return self._data[key]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/bin/procmux", line 8, in <module>
    sys.exit(start_cli())
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/procmux.py", line 8, in start_cli
    run_app(config)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/__main__.py", line 14, in run_app
    start_tui(cfg)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/tui/app.py", line 66, in start_tui
    application.run()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 736, in run
    return run()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 710, in run
    return f.result()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/eventloop/future.py", line 151, in result
    raise self._exception
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.throw(exc)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 685, in _run_async2
    result = yield f
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/eventloop/coroutine.py", line 88, in step_next
    new_f = coroutine.send(None)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 628, in _run_async
    self._redraw()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 471, in _redraw
    self.renderer.render(self, self.layout)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 582, in render
    layout.container.write_to_screen(screen, mouse_handlers, WritePosition(
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 656, in write_to_screen
    self.content.write_to_screen(
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 2234, in write_to_screen
    self._get_container().write_to_screen(*a, **kw)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 314, in write_to_screen
    c.write_to_screen(screen, mouse_handlers,
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 2196, in write_to_screen
    return self.content.write_to_screen(
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 1448, in write_to_screen
    draw_func()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/containers.py", line 1466, in _write_to_screen_at_index
    ui_content = self.content.create_content(
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/controls.py", line 323, in create_content
    fragments_with_mouse_handlers = self._get_formatted_text_cached()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/controls.py", line 304, in _get_formatted_text_cached
    return self._fragment_cache.get(
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/cache.py", line 38, in get
    value = getter_func()
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/layout/controls.py", line 306, in <lambda>
    lambda: to_formatted_text(self.text, self.style))
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/formatted_text/base.py", line 45, in to_formatted_text
    return to_formatted_text(value(), style=style)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/tui/view/help.py", line 32, in _get_formatted_text
    result = [self._get_key_combo_text(help_) for help_ in self._controller.get_app_keybindings().help_docs]
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/tui/controller/tui_controller.py", line 375, in get_app_keybindings
    self._add_side_bar_keybindings(kb)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/tui/controller/tui_controller.py", line 428, in _add_side_bar_keybindings
    kb.register_configured_keybinding_sans_event(
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/tui/keybindings.py", line 22, in register_configured_keybinding_sans_event
    self.register_configured_keybinding(keys, lambda _: handler(), help_label=help_label)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/app/tui/keybindings.py", line 33, in register_configured_keybinding
    @self.add(keybinding)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 189, in add
    keys = tuple(_check_and_expand_key(k) for k in keys)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 189, in <genexpr>
    keys = tuple(_check_and_expand_key(k) for k in keys)
  File "/home/matthieu/.cache/pypoetry/virtualenvs/server--_HPI2hw-py3.10/lib/python3.10/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 329, in _check_and_expand_key
    key = KEY_ALIASES.get(key, key)
TypeError: unhashable type: 'collections.OrderedDict'
```
I debugged it to the "docs" key in the config file using the question mark:
```
keybinding:
  docs:
    - ?
```
it decodes to `{'keybinding': {'docs': [{None: None}]}}`, because ? is interpreted as a complex mapping key 
-> a solution is to quote the ? to get a "?" string instead

**Comment by ken4647** [comment]
Thanks for your issues @rienafairefr , help me a lot! 
This issue seems to be a simple promble, however, it has been a long time for unsolved. can you@napisani solve this issue?(changing `Readme.md` is enough, but a more complete manual is better). I find this cmd tools is pretty suitable for ROS to operate so many nodes, while other tools are not such convient. I believe this project has a lot of potential in the future.
